# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            LEON DU STAR
tagline:          É˜lectronic funk music live-artist from Europe
url:              http://test.leondustar.nl
baseurl:          
paginate:         6
author:
  name:           Leon Du Star
  url:            https://twitter.com/leondustar.nl
  email:          info@leondustar.nl

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/coderofsalvation/blog.leondustar

embed_twitter: |
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
